/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author admin
 */
import Controller.BorrowsJpaController;
import Model.Borrows;
import Utility.CustomTableModel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

public class BorrowPanel extends javax.swing.JPanel
{

    /**
     * Creates new form BorrowPanel
     */
    List<Borrows> borrowList;
    int newHeight;
    int newWidth;

    public BorrowPanel(int width, int height)
    {
        initComponents();
        
        newHeight = height;
        newWidth = width;

        customizePalette();

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bookTitleName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setName("Mượn sách"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 550));

        jPanelTable.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelTable.setPreferredSize(new java.awt.Dimension(466, 484));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "No.", "Độc giả", "Tên sách", "Mã sách", "Ngày trả dự kiến", "Ngày trả"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(204, 204, 255));
        jTable1.setRowHeight(28);
        jTable1.setShowGrid(true);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelTop.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelTop.setPreferredSize(new java.awt.Dimension(743, 50));

        jLabel1.setText("Nhập tên:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        bookTitleName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bookTitleName.setPreferredSize(new java.awt.Dimension(200, 28));

        btnAdd.setBackground(new java.awt.Color(153, 255, 153));
        btnAdd.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(56, 138, 52));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_plus_math_16px.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(56, 138, 52)));
        btnAdd.setContentAreaFilled(false);
        btnAdd.setIconTextGap(10);
        btnAdd.setPreferredSize(new java.awt.Dimension(90, 28));
        btnAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 188, 253));
        btnEdit.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 83, 156));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_eraser_16px.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 83, 156)));
        btnEdit.setContentAreaFilled(false);
        btnEdit.setIconTextGap(10);
        btnEdit.setPreferredSize(new java.awt.Dimension(90, 28));
        btnEdit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 123, 255));
        btnDelete.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(161, 38, 13));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_trash_can_16px_1.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(161, 38, 13)));
        btnDelete.setContentAreaFilled(false);
        btnDelete.setIconTextGap(10);
        btnDelete.setPreferredSize(new java.awt.Dimension(90, 28));
        btnDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bookTitleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(bookTitleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                    .addComponent(jPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddActionPerformed
    {//GEN-HEADEREND:event_btnAddActionPerformed
        BorrowAddPanel borrowAdd = new BorrowAddPanel();
        
        // Open in new tab
        Home topFrame = (Home) this.getTopLevelAncestor();
        topFrame.addCard(borrowAdd);
        topFrame.showPanel(borrowAdd.getName());
        topFrame.addTab(borrowAdd.getName());
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEditActionPerformed
    {//GEN-HEADEREND:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteActionPerformed
    {//GEN-HEADEREND:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookTitleName;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void customizePalette()
    {
        btnAdd.setBorderPainted(true);
        btnAdd.setFocusPainted(false);
        btnAdd.setContentAreaFilled(false);

        // Design table header
        JTableHeader header = jTable1.getTableHeader();
        header.setOpaque(false);
        header.setBackground(new Color(135,178,253));
        header.setForeground(Color.white);
        
        header.setPreferredSize(new Dimension(454, 34));
        header.setFont(new Font("sansserif", Font.PLAIN, 12));
    }

    private void populateTable()
    {
        borrowList = new ArrayList<>(BorrowsJpaController.findBorrowsEntities());
        var maxRow = (newHeight - this.getPreferredSize().height + jScrollPane1.getViewport().getPreferredSize().height) / 28;
        
        String[] columnName =
        {
            "No.", "Họ và tên", "Tên sách", "Mã sách", "Ngày trả dự kiến", "Ngày trả"
        };

        // Create model booktitles by creating anonymous nest class of CustomTableModel<T>
        CustomTableModel<Borrows> model = new CustomTableModel<Borrows>(borrowList.size() <= maxRow? 
                borrowList : borrowList.subList(0, maxRow - 1), columnName)
        {
            @Override
            public Object getValueAt(int rowIndex, int columnIndex)
            {
                Object temp = null;
                Borrows borrow = getDataObject(rowIndex);
                switch (columnIndex)
                {
                    case 0:
                        return temp = rowIndex + 1;
                    case 1:
                        return temp = borrow.getReaderId().getFullName();
                    case 2:
                        return temp = borrow.getBookId().getBookTitleId().getTitle();
                    case 3:
                        return temp = borrow.getBookId().getCode();
                    case 4:
                        return temp = borrow.getPlanReturnDate();
                    case 5:
                        if (borrow.getReturnDate() == null)
                        {
                            return temp = "Chưa trả";
                        }
                        else
                        {
                            return temp = borrow.getReturnDate();
                        }
                    default:
                        throw new ArrayIndexOutOfBoundsException(columnIndex);
                }
            }

        };

        jTable1.setModel(model);

        jScrollPane1.getViewport().add(jTable1);
        customizeColumns();
        jPanelTable.setLayout(new BorderLayout());
        jPanelTable.add(jScrollPane1);
        jPanelTable.validate();

        jPanelTable.setVisible(true);
    }

    private void customizeColumns()
    {
        int remainWidth = newWidth - 30 - 250 - 200 - 200;
        int autoSize = Math.round(remainWidth * 0.6f);

        int[] columnWidth =
        {
            30, remainWidth - autoSize, autoSize, 200, 200, 200
        };
        
        //Design table column
        TableColumnModel columnModel = jTable1.getColumnModel();
        for (int i = 0; i < columnWidth.length; i++)
        {
            var column = columnModel.getColumn(i);
            column.setMinWidth(columnWidth[i]);
            column.setMaxWidth(columnWidth[i]);
            column.setPreferredWidth(columnWidth[i]);
        }
    }

}
