/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CategoriesJpaController;
import Controller.CountriesJpaController;
import Controller.PublishersJpaController;
import Model.Categories;
import Model.Countries;
import Model.Publishers;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame
{

    /**
     * Creates new form Home
     */
    List<JPanel> panes = new ArrayList<>();
    List<JPanel> indicators = new ArrayList<>();
    List<TabPanel> tabList = new ArrayList<>();
    
    private ArrayList<Categories> categories;
    private ArrayList<Countries> countries;
    private ArrayList<Publishers> publishers;
    
    public Home()
    {
        initComponents();
        customizeFrame();

        panes.addAll(Arrays.asList(jPanel_Title, jPanel_Store, jPanel_Reader, jPanel_Borrow, jPanel_Report, jPanel_Users));
        indicators.addAll(Arrays.asList(ind_1, ind_2, ind_3, ind_4, ind_5, ind_6));

        setColor(jPanel_Title);
        ind_1.setOpaque(true);

        decolorUnselected(jPanel_Title, ind_1);

        setTitle("PHẦN MỀM QUẢN LÝ THƯ VIỆN");
        categories = new ArrayList<>(CategoriesJpaController.findCategoriesEntities());
        countries = new ArrayList<>(CountriesJpaController.findCountriesEntities());
        publishers = new ArrayList<>(PublishersJpaController.findPublishersEntities());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        side_pane = new javax.swing.JPanel();
        jPanel_Title = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jlbBookTitle = new javax.swing.JLabel();
        jPanel_Store = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jlbBook = new javax.swing.JLabel();
        jPanel_Borrow = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel_Users = new javax.swing.JPanel();
        ind_5 = new javax.swing.JPanel();
        jLabel_Users = new javax.swing.JLabel();
        jPanel_Reader = new javax.swing.JPanel();
        ind_6 = new javax.swing.JPanel();
        jlbBook1 = new javax.swing.JLabel();
        jPanel_Report = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel_Logo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mainView = new javax.swing.JPanel();
        jPanel_Top = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_Exit = new javax.swing.JLabel();
        jLabel_Minimize = new javax.swing.JLabel();
        jLabel_Minimize1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel_TabPane = new javax.swing.JPanel();
        jPanel_Content = new javax.swing.JPanel();
        jPanel_Footer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management");
        setBackground(new java.awt.Color(243, 245, 249));
        setLocationByPlatform(true);
        setUndecorated(true);

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Title.setBackground(new java.awt.Color(23, 35, 51));
        jPanel_Title.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jPanel_TitleMouseClicked(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jlbBookTitle.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jlbBookTitle.setForeground(new java.awt.Color(255, 255, 255));
        jlbBookTitle.setText("Tên sách");

        javax.swing.GroupLayout jPanel_TitleLayout = new javax.swing.GroupLayout(jPanel_Title);
        jPanel_Title.setLayout(jPanel_TitleLayout);
        jPanel_TitleLayout.setHorizontalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jlbBookTitle)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_TitleLayout.setVerticalGroup(
            jPanel_TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_TitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBookTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(jPanel_Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 180, -1));

        jPanel_Store.setBackground(new java.awt.Color(23, 35, 51));
        jPanel_Store.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPanel_StoreMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jlbBook.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jlbBook.setForeground(new java.awt.Color(255, 255, 255));
        jlbBook.setText("Kho sách");

        javax.swing.GroupLayout jPanel_StoreLayout = new javax.swing.GroupLayout(jPanel_Store);
        jPanel_Store.setLayout(jPanel_StoreLayout);
        jPanel_StoreLayout.setHorizontalGroup(
            jPanel_StoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_StoreLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jlbBook, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel_StoreLayout.setVerticalGroup(
            jPanel_StoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_StoreLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_StoreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(jPanel_Store, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, -1));

        jPanel_Borrow.setBackground(new java.awt.Color(23, 35, 51));
        jPanel_Borrow.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPanel_BorrowMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mượn/Trả sách");

        javax.swing.GroupLayout jPanel_BorrowLayout = new javax.swing.GroupLayout(jPanel_Borrow);
        jPanel_Borrow.setLayout(jPanel_BorrowLayout);
        jPanel_BorrowLayout.setHorizontalGroup(
            jPanel_BorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BorrowLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addGap(0, 62, Short.MAX_VALUE))
        );
        jPanel_BorrowLayout.setVerticalGroup(
            jPanel_BorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BorrowLayout.createSequentialGroup()
                .addGroup(jPanel_BorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_pane.add(jPanel_Borrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 180, 40));

        jPanel_Users.setBackground(new java.awt.Color(23, 35, 51));
        jPanel_Users.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jPanel_UsersMouseClicked(evt);
            }
        });

        ind_5.setOpaque(false);
        ind_5.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_5Layout = new javax.swing.GroupLayout(ind_5);
        ind_5.setLayout(ind_5Layout);
        ind_5Layout.setHorizontalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_5Layout.setVerticalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel_Users.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel_Users.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Users.setText("Tài khoản");

        javax.swing.GroupLayout jPanel_UsersLayout = new javax.swing.GroupLayout(jPanel_Users);
        jPanel_Users.setLayout(jPanel_UsersLayout);
        jPanel_UsersLayout.setHorizontalGroup(
            jPanel_UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_UsersLayout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel_Users)
                .addGap(0, 91, Short.MAX_VALUE))
        );
        jPanel_UsersLayout.setVerticalGroup(
            jPanel_UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_UsersLayout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_UsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(jPanel_Users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 180, -1));

        jPanel_Reader.setBackground(new java.awt.Color(23, 35, 51));
        jPanel_Reader.setPreferredSize(new java.awt.Dimension(180, 43));
        jPanel_Reader.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jPanel_ReaderMouseClicked(evt);
            }
        });

        ind_6.setOpaque(false);
        ind_6.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_6Layout = new javax.swing.GroupLayout(ind_6);
        ind_6.setLayout(ind_6Layout);
        ind_6Layout.setHorizontalGroup(
            ind_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_6Layout.setVerticalGroup(
            ind_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jlbBook1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jlbBook1.setForeground(new java.awt.Color(255, 255, 255));
        jlbBook1.setText("Bạn đọc");

        javax.swing.GroupLayout jPanel_ReaderLayout = new javax.swing.GroupLayout(jPanel_Reader);
        jPanel_Reader.setLayout(jPanel_ReaderLayout);
        jPanel_ReaderLayout.setHorizontalGroup(
            jPanel_ReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ReaderLayout.createSequentialGroup()
                .addComponent(ind_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jlbBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel_ReaderLayout.setVerticalGroup(
            jPanel_ReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ReaderLayout.createSequentialGroup()
                .addGroup(jPanel_ReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ind_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbBook1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_pane.add(jPanel_Reader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, -1));

        jPanel_Report.setBackground(new java.awt.Color(23, 35, 51));
        jPanel_Report.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jPanel_ReportMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Thống kê");

        javax.swing.GroupLayout jPanel_ReportLayout = new javax.swing.GroupLayout(jPanel_Report);
        jPanel_Report.setLayout(jPanel_ReportLayout);
        jPanel_ReportLayout.setHorizontalGroup(
            jPanel_ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ReportLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(0, 93, Short.MAX_VALUE))
        );
        jPanel_ReportLayout.setVerticalGroup(
            jPanel_ReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ReportLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_ReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(jPanel_Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 180, -1));

        jPanel_Logo.setBackground(new java.awt.Color(0, 0, 0));
        jPanel_Logo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(5, 45, 55));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/logo-2.png"))); // NOI18N
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel_LogoLayout = new javax.swing.GroupLayout(jPanel_Logo);
        jPanel_Logo.setLayout(jPanel_LogoLayout);
        jPanel_LogoLayout.setHorizontalGroup(
            jPanel_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );
        jPanel_LogoLayout.setVerticalGroup(
            jPanel_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LogoLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        side_pane.add(jPanel_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 185, 82));

        mainView.setBackground(new java.awt.Color(23, 35, 51));
        mainView.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(23, 35, 51), 1, true));
        mainView.setPreferredSize(new java.awt.Dimension(1009, 590));

        jPanel_Top.setBackground(new java.awt.Color(240, 239, 241));
        jPanel_Top.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel_Top.setPreferredSize(new java.awt.Dimension(1009, 40));

        jPanel4.setBackground(new java.awt.Color(240, 239, 241));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel4.setPreferredSize(new java.awt.Dimension(102, 34));

        jLabel_Exit.setBackground(new java.awt.Color(161, 38, 13));
        jLabel_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_delete_16px_3.png"))); // NOI18N
        jLabel_Exit.setPreferredSize(new java.awt.Dimension(36, 36));

        jLabel_Minimize.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_horizontal_line_16px_9.png"))); // NOI18N
        jLabel_Minimize.setPreferredSize(new java.awt.Dimension(36, 36));

        jLabel_Minimize1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_Minimize1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Minimize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_maximize_button_16px.png"))); // NOI18N
        jLabel_Minimize1.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_Minimize1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel_Minimize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel_Minimize1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.setBackground(new java.awt.Color(240, 239, 241));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(102, 34));

        jLabel3.setBackground(new java.awt.Color(240, 239, 241));
        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(56, 138, 52));
        jLabel3.setText("Xin chào Super Admin!");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 7));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(41, 26));

        jLabel8.setBackground(new java.awt.Color(240, 239, 241));
        jLabel8.setForeground(new java.awt.Color(0, 83, 156));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_export_16px_2.png"))); // NOI18N
        jLabel8.setText("Đăng xuất");
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel8.setIconTextGap(10);
        jLabel8.setPreferredSize(new java.awt.Dimension(90, 26));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel_TopLayout = new javax.swing.GroupLayout(jPanel_Top);
        jPanel_Top.setLayout(jPanel_TopLayout);
        jPanel_TopLayout.setHorizontalGroup(
            jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TopLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_TopLayout.setVerticalGroup(
            jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel_TabPane.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_TabPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel_TabPane.setPreferredSize(new java.awt.Dimension(1009, 40));
        jPanel_TabPane.setLayout(new javax.swing.BoxLayout(jPanel_TabPane, javax.swing.BoxLayout.LINE_AXIS));

        jPanel_Content.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Content.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel_Content.setPreferredSize(new java.awt.Dimension(1009, 451));
        jPanel_Content.setLayout(new java.awt.CardLayout());

        jPanel_Footer.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Footer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel_Footer.setPreferredSize(new java.awt.Dimension(1009, 25));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 25));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("© 2020 Copyright by ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mr. Lorem Ipsum ");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setText("|");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setPreferredSize(new java.awt.Dimension(4, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Contact me: loremIpsum@gmail.com");
        jLabel7.setPreferredSize(new java.awt.Dimension(117, 18));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        javax.swing.GroupLayout jPanel_FooterLayout = new javax.swing.GroupLayout(jPanel_Footer);
        jPanel_Footer.setLayout(jPanel_FooterLayout);
        jPanel_FooterLayout.setHorizontalGroup(
            jPanel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FooterLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel_FooterLayout.setVerticalGroup(
            jPanel_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOpaque(true);
        jSeparator1.setPreferredSize(new java.awt.Dimension(1009, 5));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOpaque(true);

        javax.swing.GroupLayout mainViewLayout = new javax.swing.GroupLayout(mainView);
        mainView.setLayout(mainViewLayout);
        mainViewLayout.setHorizontalGroup(
            mainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Top, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
            .addComponent(jPanel_TabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel_Footer, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
            .addComponent(jPanel_Content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
            .addComponent(jSeparator2)
        );
        mainViewLayout.setVerticalGroup(
            mainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainViewLayout.createSequentialGroup()
                .addComponent(jPanel_Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_TabPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_Content, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(side_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainView, 1015, 1015, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(side_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel_StoreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_StoreMousePressed
        // TODO add your handling code here:
        setColor(jPanel_Store);
        ind_3.setOpaque(true);
        decolorUnselected(jPanel_Store, ind_3);

        // Add to Jpanel_Content
        // Get size to scale jpanels inside jpanel_Content
        var height = jPanel_Content.getSize().height;
        var width = jPanel_Content.getSize().width;
        
        BookStockPanel stockPanel = new BookStockPanel(width, height);
        var name = stockPanel.getName();
        jPanel_Content.removeAll();
        jPanel_Content.add(stockPanel, name);
        showPanel(name);

        jPanel_TabPane.removeAll();
        tabList.clear();
        addTab(name);
    }//GEN-LAST:event_jPanel_StoreMousePressed

    private void jPanel_BorrowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_BorrowMousePressed
        // TODO add your handling code here:
        setColor(jPanel_Borrow);
        ind_4.setOpaque(true);
        decolorUnselected(jPanel_Borrow, ind_4);

        // Add to Jpanel_Content
        // Get size to scale jpanels inside jpanel_Content
        var height = jPanel_Content.getSize().height;
        var width = jPanel_Content.getSize().width;
        
        BorrowPanel borrowPanel = new BorrowPanel(width, height);
        var name = borrowPanel.getName();
        jPanel_Content.removeAll();
        jPanel_Content.add(borrowPanel, name);
        showPanel(name);

        jPanel_TabPane.removeAll();
        tabList.clear();
        addTab(name);
    }//GEN-LAST:event_jPanel_BorrowMousePressed

    private void jPanel_ReportMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_ReportMouseReleased
        // TODO add your handling code here:
        setColor(jPanel_Report);
        ind_2.setOpaque(true);

        decolorUnselected(jPanel_Report, ind_2);

        // Add to Jpanel_Content
//        mainView.removeAll();
//        mainView.revalidate();
//        mainView.repaint();
    }//GEN-LAST:event_jPanel_ReportMouseReleased

    private void jPanel_TitleMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel_TitleMouseClicked
    {//GEN-HEADEREND:event_jPanel_TitleMouseClicked
        // TODO add your handling code here:
        setColor(jPanel_Title);
        ind_1.setOpaque(true);

        decolorUnselected(jPanel_Title, ind_1);

        // Add to Jpanel_Content
        // Get size to scale jpanels inside jpanel_Content
        var height = jPanel_Content.getSize().height;
        var width = jPanel_Content.getSize().width;
        BookTitlePanel bookTitlePanel = new BookTitlePanel(width, height, categories, countries, publishers);
        var name = bookTitlePanel.getName();
        jPanel_Content.removeAll();
        jPanel_Content.add(bookTitlePanel, name);
        showPanel(name);

        jPanel_TabPane.removeAll();
        tabList.clear();
        addTab(name);
    }//GEN-LAST:event_jPanel_TitleMouseClicked

    private void jPanel_UsersMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel_UsersMouseClicked
    {//GEN-HEADEREND:event_jPanel_UsersMouseClicked
        // TODO add your handling code here:
        setColor(jPanel_Users);
        ind_5.setOpaque(true);

        decolorUnselected(jPanel_Users, ind_5);

        // Add to Jpanel_Content
        // Get size to scale jpanels inside jpanel_Content
        var height = jPanel_Content.getSize().height;
        var width = jPanel_Content.getSize().width;
        
        UsersPanel usersPanel = new UsersPanel(width, height);
        var name = usersPanel.getName();
        jPanel_Content.removeAll();
        jPanel_Content.add(usersPanel, name);
        showPanel(name);

        jPanel_TabPane.removeAll();
        tabList.clear();
        addTab(name);
    }//GEN-LAST:event_jPanel_UsersMouseClicked

    private void jPanel_ReaderMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel_ReaderMouseClicked
    {//GEN-HEADEREND:event_jPanel_ReaderMouseClicked
        // TODO add your handling code here:
        setColor(jPanel_Reader);
        ind_6.setOpaque(true);

        decolorUnselected(jPanel_Reader, ind_6);

        // Add to Jpanel_Content
        // Get size to scale jpanels inside jpanel_Content
        var height = jPanel_Content.getSize().height;
        var width = jPanel_Content.getSize().width;
        
        ReaderPanel readerPanel = new ReaderPanel(width, height);
        var name = readerPanel.getName();
        jPanel_Content.removeAll();
        jPanel_Content.add(readerPanel, name);
        showPanel(name);

        jPanel_TabPane.removeAll();
        tabList.clear();
        addTab(name);
    }//GEN-LAST:event_jPanel_ReaderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Home().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_5;
    private javax.swing.JPanel ind_6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Exit;
    private javax.swing.JLabel jLabel_Minimize;
    private javax.swing.JLabel jLabel_Minimize1;
    private javax.swing.JLabel jLabel_Users;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_Borrow;
    private javax.swing.JPanel jPanel_Content;
    private javax.swing.JPanel jPanel_Footer;
    private javax.swing.JPanel jPanel_Logo;
    private javax.swing.JPanel jPanel_Reader;
    private javax.swing.JPanel jPanel_Report;
    private javax.swing.JPanel jPanel_Store;
    private javax.swing.JPanel jPanel_TabPane;
    private javax.swing.JPanel jPanel_Title;
    private javax.swing.JPanel jPanel_Top;
    private javax.swing.JPanel jPanel_Users;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlbBook;
    private javax.swing.JLabel jlbBook1;
    private javax.swing.JLabel jlbBookTitle;
    private javax.swing.JPanel mainView;
    private javax.swing.JPanel side_pane;
    // End of variables declaration//GEN-END:variables

    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(List<JPanel> panes, List<JPanel> indicators)
    {
        panes.forEach((pane) ->
        {
            pane.setBackground(new Color(23, 35, 51));
        });

        indicators.forEach((indicator) ->
        {
            indicator.setOpaque(false);
        });
    }

    private void decolorUnselected(JPanel pane, JPanel indicator)
    {
        var subPanes = panes.stream().filter(obj -> obj != pane).collect(Collectors.toList());
        var subIndi = indicators.stream().filter(obj -> obj != indicator).collect(Collectors.toList());
        resetColor(subPanes, subIndi);
    }

    private void customizeFrame()
    {
        
        setLayout(new BorderLayout());
        add(side_pane, BorderLayout.LINE_START);
        add(mainView, BorderLayout.CENTER);
        setExtendedState(getExtendedState() | MAXIMIZED_BOTH);
    }

    private void tab_MouseClick(MouseEvent evt)
    {
        showPanel(evt.getComponent().getName());
    }

    public void showPanel(String name)
    {
        CardLayout c1 = (CardLayout) jPanel_Content.getLayout();

        c1.show(jPanel_Content, name);
    }

    public void addTab(String name)
    {
        TabPanel newTab = new TabPanel(name);
        // add click event to switch among tabs
        newTab.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent evt)
            {
                tab_MouseClick(evt);
            }

        });

        jPanel_TabPane.add(newTab);
        jPanel_TabPane.revalidate();
        jPanel_TabPane.repaint();
        tabList.add(newTab);
    }

    public void addCard(JPanel jPanel)
    {
        jPanel_Content.add(jPanel, jPanel.getName());
    }

    class TabPanel extends JPanel
    {

        JLabel label_Title;

        public TabPanel(String title)
        {
            super();
            customizePanel(title);
        }

        private void customizePanel(String title)
        {
            this.setName(title);
            if (tabList.isEmpty())
            {
                label_Title = new JLabel(title);
            }
            else
            {
                label_Title = new JLabel(" /   " + title);
            }
            
            var size = label_Title.getPreferredSize().width;
            this.setBackground(new java.awt.Color(255, 255, 255));
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            this.setPreferredSize(new java.awt.Dimension(size, 25));

            javax.swing.GroupLayout jPanel_TabLayout = new javax.swing.GroupLayout(this);
            this.setLayout(jPanel_TabLayout);
            jPanel_TabLayout.setHorizontalGroup(jPanel_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_TabLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(label_Title, javax.swing.GroupLayout.PREFERRED_SIZE, size, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)
                            .addContainerGap())
            );
            jPanel_TabLayout.setVerticalGroup(jPanel_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_TabLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                            .addContainerGap())
            );
        }

    }
}
