/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BookTitlesJpaController;
import Controller.ReadersJpaController;
import Controller.exceptions.NonexistentEntityException;
import Model.BookTitles;
import Model.Readers;
import Utility.CustomTableModel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 * S
 *
 * @author admin
 */
public class ReaderPanel extends javax.swing.JPanel
{

    /**
     * Creates new form ReaderPanel
     */
    List<Readers> readers;
    int newHeight;
    int newWidth;
    
    int maxPage = 1;
    int currentPage = 1;
    int maxRow;

    boolean nextListenerOnOff = true;
    boolean backListenerOnOff = true;

    public ReaderPanel(int width, int height)
    {
        initComponents();

        newHeight = height;
        newWidth = width;

        customizePalette();

        customizeTable();

        populateTable(currentPage);
        setPageNoColor();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bookTitleName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanelTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel_Paging = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_First = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel_Back = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel_PageNo = new javax.swing.JPanel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel_Next = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel_Last = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setName("Bạn đọc"); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 546));

        jPanelTop.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelTop.setPreferredSize(new java.awt.Dimension(554, 50));

        jLabel1.setText("Nhập tên:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        bookTitleName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bookTitleName.setPreferredSize(new java.awt.Dimension(200, 28));

        btnAdd.setBackground(new java.awt.Color(153, 255, 153));
        btnAdd.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(56, 138, 52));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_plus_math_16px.png"))); // NOI18N
        btnAdd.setText(" Thêm ");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(56, 138, 52)));
        btnAdd.setContentAreaFilled(false);
        btnAdd.setIconTextGap(10);
        btnAdd.setPreferredSize(new java.awt.Dimension(90, 28));
        btnAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 188, 253));
        btnEdit.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 83, 156));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_eraser_16px.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 83, 156)));
        btnEdit.setContentAreaFilled(false);
        btnEdit.setIconTextGap(10);
        btnEdit.setPreferredSize(new java.awt.Dimension(90, 28));
        btnEdit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 123, 255));
        btnDelete.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(161, 38, 13));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_trash_can_16px_1.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(161, 38, 13)));
        btnDelete.setContentAreaFilled(false);
        btnDelete.setIconTextGap(10);
        btnDelete.setPreferredSize(new java.awt.Dimension(90, 28));
        btnDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bookTitleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bookTitleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jPanelTable.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelTable.setPreferredSize(new java.awt.Dimension(466, 430));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "No.", "Độc giả", "Số thẻ", "Số CCCD", "Ngày sinh", "Giới tính", "Địa chỉ", "Điện thoại", "Quốc tịch", "Nghề nghiệp", "Cơ quan"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(204, 204, 255));
        jTable1.setRowHeight(28);
        jTable1.setShowGrid(true);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTableLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel_Paging.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Paging.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel_Paging.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel_Paging.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel_First.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_First.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel_First.setForeground(new java.awt.Color(0, 83, 156));
        jLabel_First.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_First.setText("Đầu");
        jLabel_First.setPreferredSize(new java.awt.Dimension(35, 30));
        jLabel_First.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel_FirstMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_First);
        jPanel1.add(filler1);

        jLabel_Back.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_less_than_16px.png"))); // NOI18N
        jLabel_Back.setPreferredSize(new java.awt.Dimension(25, 30));
        jLabel_Back.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel_BackMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_Back);
        jPanel1.add(filler2);

        jPanel_PageNo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_PageNo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel_PageNo.setPreferredSize(new java.awt.Dimension(117, 40));
        jPanel_PageNo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 12, 8));
        jPanel1.add(jPanel_PageNo);
        jPanel1.add(filler5);

        jLabel_Next.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_more_than_16px.png"))); // NOI18N
        jLabel_Next.setPreferredSize(new java.awt.Dimension(25, 30));
        jLabel_Next.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel_NextMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_Next);
        jPanel1.add(filler4);

        jLabel_Last.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Last.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel_Last.setForeground(new java.awt.Color(0, 83, 156));
        jLabel_Last.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Last.setText("Cuối");
        jLabel_Last.setPreferredSize(new java.awt.Dimension(35, 30));
        jLabel_Last.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLabel_LastMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_Last);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel_Paging.add(jPanel1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addComponent(jPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addComponent(jPanel_Paging, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Paging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddActionPerformed
    {//GEN-HEADEREND:event_btnAddActionPerformed
        ReaderAddPanel readerAdd = new ReaderAddPanel();
        
        // Open readerAdd in new tab
        Home topFrame = (Home) this.getTopLevelAncestor();
        topFrame.addCard(readerAdd);
        topFrame.showPanel(readerAdd.getName());
        topFrame.addTab(readerAdd.getName());
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEditActionPerformed
    {//GEN-HEADEREND:event_btnEditActionPerformed
        // TODO add your handling code here:
        int id = (int) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 11);
        
        ReaderEditPanel panel = new ReaderEditPanel(id);
        
        // Open panel in new tab
        Home topFrame = (Home) this.getTopLevelAncestor();
        topFrame.addCard(panel);
        topFrame.showPanel(panel.getName());
        topFrame.addTab(panel.getName());
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteActionPerformed
    {//GEN-HEADEREND:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int id = (int) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 11);
        
        try
        {
            ReadersJpaController.destroy(id);
            
            populateTable(currentPage);
            
            JOptionPane.showMessageDialog(null, "Xóa thông tin thành công", "Thông báo", JOptionPane.OK_OPTION);
        }
        catch (NonexistentEntityException ex)
        {
            Logger.getLogger(ReaderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jLabel_FirstMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel_FirstMouseClicked
    {//GEN-HEADEREND:event_jLabel_FirstMouseClicked
        // TODO add your handling code here:
        currentPage = 1;

        // Populate jtable
        populateTable(currentPage);
        setPageNoColor();

        // Set page button
        if (maxPage > 3)
        {
            jLabel_Back.setEnabled(false);
            backListenerOnOff = false;

            if (!nextListenerOnOff)
            {
                nextListenerOnOff = true;
            }
        }

        // add page number
        jPanel_PageNo.removeAll();
        for (int i = 1; i < 4; i++)
        {
            JLabel label = createPageNumber(i);
            jPanel_PageNo.add(label);
        }
        jPanel_PageNo.revalidate();
    }//GEN-LAST:event_jLabel_FirstMouseClicked

    private void jLabel_BackMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel_BackMouseClicked
    {//GEN-HEADEREND:event_jLabel_BackMouseClicked
        // TODO add your handling code here:

        if (backListenerOnOff)
        {
            if (!nextListenerOnOff)
            {
                nextListenerOnOff = true;
            }

            var firstNumber = Integer.parseInt(jPanel_PageNo.getComponents()[0].getName());
            jPanel_PageNo.removeAll();

            for (int i = 3; i > 0; i--)
            {
                int pageNumber = firstNumber - i;

                if (pageNumber >= 1)
                {
                    JLabel label = createPageNumber(pageNumber);
                    jPanel_PageNo.add(label);

                    if (pageNumber == 1)
                    {
                        jLabel_Back.setEnabled(false);
                        backListenerOnOff = false;
                    }
                }
            }
            jPanel_PageNo.revalidate();

            currentPage = firstNumber - 3;
            populateTable(currentPage);
            setPageNoColor();
        }
    }//GEN-LAST:event_jLabel_BackMouseClicked

    private void jLabel_NextMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel_NextMouseClicked
    {//GEN-HEADEREND:event_jLabel_NextMouseClicked
        // TODO add your handling code here:

        if (nextListenerOnOff)
        {
            if (!backListenerOnOff)
            {
                backListenerOnOff = true;
            }

            var lastNumber = Integer.parseInt(jPanel_PageNo.getComponents()[2].getName());
            jPanel_PageNo.removeAll();

            for (int i = 1; i < 4; i++)
            {

                int pageNumber = lastNumber + i;

                if (pageNumber <= maxPage)
                {
                    JLabel label = createPageNumber(pageNumber);
                    jPanel_PageNo.add(label);

                    if (pageNumber == maxPage)
                    {
                        jLabel_Next.setEnabled(false);
                        nextListenerOnOff = false;
                    }
                }
            }

            jPanel_PageNo.revalidate();

            currentPage = lastNumber + 1;
            populateTable(currentPage);
            setPageNoColor();
        }
    }//GEN-LAST:event_jLabel_NextMouseClicked

    private void jLabel_LastMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel_LastMouseClicked
    {//GEN-HEADEREND:event_jLabel_LastMouseClicked
        // TODO add your handling code here:
        currentPage = maxPage;

        // Populate jtable
        populateTable(currentPage);
        setPageNoColor();

        // Set page button
        if (maxPage > 3)
        {
            jLabel_Next.setEnabled(false);
            nextListenerOnOff = false;

            if (!backListenerOnOff)
            {
                backListenerOnOff = true;
            }
        }

        // add page number
        jPanel_PageNo.removeAll();
        for (int i = maxPage; i > maxPage - 3; i--)
        {
            JLabel label = createPageNumber(i);
            jPanel_PageNo.add(label);
        }
        jPanel_PageNo.revalidate();
    }//GEN-LAST:event_jLabel_LastMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookTitleName;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Back;
    private javax.swing.JLabel jLabel_First;
    private javax.swing.JLabel jLabel_Last;
    private javax.swing.JLabel jLabel_Next;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JPanel jPanel_PageNo;
    private javax.swing.JPanel jPanel_Paging;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void customizePalette()
    {
        btnAdd.setBorderPainted(true);
        btnAdd.setFocusPainted(false);
        btnAdd.setContentAreaFilled(false);

        // Design table header
        JTableHeader header = jTable1.getTableHeader();
        header.setOpaque(false);
        header.setBackground(new Color(135, 178, 253));
        header.setForeground(Color.white);

        header.setPreferredSize(new Dimension(454, 34));
        header.setFont(new Font("sansserif", Font.PLAIN, 12));
    }

    private void populateTable(int page)
    {
        

        String[] columnName =
        {
            "No.", "Tên", "Số thẻ", "Quốc tịch", "Số CCCD", "Ngày sinh", "Giới tính", "Địa chỉ", "Điện thoại", "Nghề nghiệp", "Cơ quan", "Id"
        };

        // Create model booktitles by creating anonymous nest class of CustomTableModel<T>
        CustomTableModel<Readers> model = new CustomTableModel<Readers>(readers.size() <= maxRow
                ? readers : readers.subList(0, maxRow - 1), columnName)
        {
            @Override
            public Object getValueAt(int rowIndex, int columnIndex)
            {
                Object temp = null;
                Readers reader = getDataObject(rowIndex);
                switch (columnIndex)
                {
                    case 0:
                        return temp = rowIndex + 1;
                    case 1:
                        return temp = reader.getFullName();
                    case 2:
                        return temp = reader.getMemberCard();
                    case 3:
                        return temp = reader.getCountryId().getName();
                    case 4:
                        return temp = reader.getIdentityCard();
                    case 5:
                        return temp = reader.getBirthDay();
                    case 6:
                        return temp = reader.getGender() ? "Nam" : "Nữ";
                    case 7:
                        return temp = reader.getAddress();
                    case 8:
                        return temp = reader.getPhone();
                    case 9:
                        return temp = reader.getJobTitle();
                    case 10:
                        return temp = reader.getWorkPlace();
                    case 11:
                        return temp = reader.getId();
                    default:
                        throw new ArrayIndexOutOfBoundsException(columnIndex);
                }
            }

        };

        jTable1.setModel(model);

        jScrollPane1.getViewport().add(jTable1);
        customizeColumns();
        jPanelTable.setLayout(new BorderLayout());
        jPanelTable.add(jScrollPane1);
        jPanelTable.validate();

        jPanelTable.setVisible(true);
    }

    private void customizeColumns()
    {
        int remainWidth = newWidth - 30 - 100 - 100 - 100 - 60 - 100 - 100 - 100 - 120 - 0;
        int autoSize = Math.round(remainWidth * 0.55f);

        int[] columnWidth =
        {
            30, autoSize, remainWidth - autoSize, 100, 100, 100, 60, 100, 100, 100, 120, 0
        };

        //Design table column
        TableColumnModel columnModel = jTable1.getColumnModel();
        for (int i = 0; i < columnWidth.length; i++)
        {
            var column = columnModel.getColumn(i);
            column.setMinWidth(columnWidth[i]);
            column.setMaxWidth(columnWidth[i]);
            column.setPreferredWidth(columnWidth[i]);
        }
    }
    
    private JLabel createPageNumber(int number)
    {
        JLabel pageLabel = new JLabel();
        pageLabel.setName(String.valueOf(number));
        pageLabel.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        pageLabel.setForeground(new java.awt.Color(0, 83, 156));
        pageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageLabel.setText(String.valueOf(number));
        pageLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        pageLabel.setPreferredSize(new java.awt.Dimension(27, 24));

        pageLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                PageNumber_MouseClicked(evt);
            }

        });

        return pageLabel;
    }

    private void PageNumber_MouseClicked(MouseEvent evt)
    {
        currentPage = Integer.parseInt(evt.getComponent().getName());
        populateTable(currentPage);

        // set color for selected pageNo
        setPageNoColor();
    }

    private void customizeTable()
    {
        // Get data
        readers = new ArrayList<>(ReadersJpaController.findReadersEntities());
        maxRow = (newHeight - this.getPreferredSize().height + jScrollPane1.getViewport().getPreferredSize().height) / 28;

        // Get number of pages
        if (readers.isEmpty())
        {
            maxPage = 1;
        }
        else
        {
            maxPage = readers.size() % maxRow == 0 ? readers.size() / maxRow : readers.size() / maxRow + 1;
        }

        // Create paging bar
        for (int i = 1; i <= maxPage; i++)
        {
            jPanel_PageNo.add(createPageNumber(i));

            if (i == 3)
            {
                break;
            }
        }

        // Set page button
        if (maxPage > 3)
        {
            jLabel_Back.setEnabled(false);
            backListenerOnOff = false;
        }
        else
        {
            jLabel_Next.setEnabled(false);
            nextListenerOnOff = false;
            jLabel_Back.setEnabled(false);
            backListenerOnOff = false;
        }
    }

    private void setPageNoColor()
    {
        for (Component component : jPanel_PageNo.getComponents())
        {
            JLabel label = (JLabel) component;
            if (Integer.parseInt(label.getName()) != currentPage)
            {
                label.setOpaque(false);
                label.repaint();
            }
            else
            {
                label.setOpaque(true);
                label.setBackground(Color.GREEN);
                label.repaint();
            }
        }
    }

}
